"バンドルプラグインを読み込む
source ~/dotfiles/vim.d/_vimrc.neoBandle

"見た目の変更
source ~/dotfiles/vim.d/_vimrc.appearence

"基本
source ~/dotfiles/vim.d/_vimrc.basic

"NeoComplcacheの設定
source ~/dotfiles/vim.d/_vimrc.neoComplache

"Unitの設定
source ~/dotfiles/vim.d/_vimrc.unit

"エンコーディング
source ~/dotfiles/vim.d/_vimrc.encoding
